//! Disk-backed project storage. Each project = a folder under <root>/projects/<id>,
//! unless `local_path` is set (then that folder is the root). Mirrors backend/storage.py.
use std::path::{Path, PathBuf};

use serde_json::{json, Value};
/// Resolve a project's root folder.
pub fn project_root(root: &Path, id: &str, local_path: Option<&str>) -> PathBuf {
    match local_path {
        Some(p) if !p.is_empty() => PathBuf::from(p),
        _ => root.join("projects").join(id),
    }
}

/// Join a relative path under a project root, rejecting traversal outside it.
pub fn safe_join(root: &Path, id: &str, local_path: Option<&str>, rel: &str) -> Result<PathBuf, String> {
    use path_clean::PathClean;
    let base = project_root(root, id, local_path);
    // lexical normalization resolves `..` so `../escape` is caught even when the
    // target file does not yet exist (canonicalize() would fail on a new file).
    let target = base.join(rel).clean();
    let base = base.clean();
    if !target.starts_with(&base) {
        return Err("path escapes project root".into());
    }
    Ok(target)
}

pub fn write_file(root: &Path, id: &str, local_path: Option<&str>, rel: &str, content: &str) -> Result<String, String> {
    let target = safe_join(root, id, local_path, rel)?;
    if let Some(parent) = target.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::write(&target, content).map_err(|e| e.to_string())?;
    Ok(rel.to_string())
}

pub fn make_dir(root: &Path, id: &str, local_path: Option<&str>, rel: &str) -> Result<String, String> {
    let target = safe_join(root, id, local_path, rel)?;
    std::fs::create_dir_all(&target).map_err(|e| e.to_string())?;
    Ok(rel.to_string())
}

pub fn read_file(root: &Path, id: &str, local_path: Option<&str>, rel: &str) -> Result<String, String> {
    let target = safe_join(root, id, local_path, rel)?;
    std::fs::read_to_string(&target).map_err(|e| e.to_string())
}

pub fn delete_path(root: &Path, id: &str, local_path: Option<&str>, rel: &str) -> Result<(), String> {
    let target = safe_join(root, id, local_path, rel)?;
    if target.is_dir() {
        std::fs::remove_dir_all(&target).map_err(|e| e.to_string())
    } else {
        std::fs::remove_file(&target).map_err(|e| e.to_string())
    }
}

pub fn move_path(root: &Path, id: &str, local_path: Option<&str>, old: &str, new: &str) -> Result<String, String> {
    let from = safe_join(root, id, local_path, old)?;
    let to = safe_join(root, id, local_path, new)?;
    if let Some(parent) = to.parent() {
        std::fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    std::fs::rename(&from, &to).map_err(|e| e.to_string())?;
    Ok(new.to_string())
}

/// The per-project `.clangd` config text (CompileFlags + clang-tidy checks).
pub fn clangd_config_text(std: &str) -> String {
    format!(
        "CompileFlags:\n  Add: [-std={std}, -Wall, -Wextra]\nDiagnostics:\n  ClangTidy:\n    Add: [bugprone-*, performance-*, readability-*, modernize-*]\n    Remove: [readability-magic-numbers, readability-identifier-length, modernize-use-trailing-return-type, readability-function-cognitive-complexity, bugprone-easily-swappable-parameters]\n"
    )
}

/// Write the per-project .clangd (for host clangd / VS Code).
pub fn write_clangd_config(root: &Path, id: &str, local_path: Option<&str>, std: &str) {
    let d = project_root(root, id, local_path);
    let _ = std::fs::create_dir_all(&d);
    let _ = std::fs::write(d.join(".clangd"), clangd_config_text(std));
}

/// Per-project Makefile so `make` builds under VS Code Remote-SSH.
pub fn write_makefile(root: &Path, id: &str, local_path: Option<&str>, std: &str) {
    let d = project_root(root, id, local_path);
    let _ = std::fs::create_dir_all(&d);
    let body = "# Auto-generated by CPPBox\n\
CXX := clang++\n\
STD := {std}\n\
CXXFLAGS := -std=$(STD) -O2 -Wall -Wextra -pedantic\n\
SRCS := $(shell find . -type f \\( -name '*.cpp' -o -name '*.cc' -o -name '*.cxx' \\))\n\
HDRS := $(shell find . -type f \\( -name '*.h' -o -name '*.hpp' -o -name '*.hh' \\))\n\
DIRS := $(sort $(dir $(SRCS) $(HDRS)) .)\n\
INCS := $(patsubst %,-I%,$(DIRS))\n\
BIN := app\n\n\
all: $(BIN)\n\
$(BIN): $(SRCS)\n\
\t$(CXX) $(CXXFLAGS) $(INCS) $(SRCS) -o $(BIN)\n\
run: all\n\
\t./$(BIN)\n\
clean:\n\
\trm -f $(BIN)\n\
.PHONY: all run clean\n".replace("{std}", std);
    let _ = std::fs::write(d.join("Makefile"), body);
}

const GITIGNORE: &str = "\
.ccls-cache/\n\
.breakpoints\n\
.prettierignore\n\
.replit\n\
*.nix\n\
main\n\
main-debug\n\
Makefile\n\
*.o\n\
app\n\
output/\n\n\
# Prerequisites\n*.d\n\n\
# Compiled Object files\n*.slo\n*.lo\n*.o\n*.obj\n\n\
# Precompiled Headers\n*.gch\n*.pch\n\n\
# Compiled Dynamic libraries\n*.so\n*.dylib\n*.dll\n\n\
# Fortran module files\n*.mod\n*.smod\n\n\
# Compiled Static libraries\n*.lai\n*.la\n*.a\n*.lib\n\n\
# Executables\n*.exe\n*.out\n*.app\n\n\
# Build artifacts\napp\n";

/// Initialize a git repo in the project folder and write .gitignore.
pub fn git_init_project(root: &Path, id: &str, local_path: Option<&str>) {
    let d = project_root(root, id, local_path);
    if !d.exists() {
        return;
    }
    let _ = std::fs::write(d.join(".gitignore"), GITIGNORE);
    let _ = std::process::Command::new("git").arg("init").current_dir(&d)
        .stdout(std::process::Stdio::null()).stderr(std::process::Stdio::null()).status();
}

/// Read every source/header file for compilation. Returns (relative_name, content).
pub fn collect_source_files(root: &Path, id: &str, local_path: Option<&str>) -> Vec<(String, String)> {
    let base = project_root(root, id, local_path);
    let mut out = Vec::new();
    if !base.exists() {
        return out;
    }
    collect_into(&base, &base, &mut out);
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

const SRC_EXTS: [&str; 8] = ["cpp", "cc", "cxx", "c", "h", "hpp", "hh", "hxx"];

fn collect_into(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || name == "__pycache__" {
            continue;
        }
        let Ok(ft) = e.file_type() else { continue };
        if ft.is_dir() {
            collect_into(base, &e.path(), out);
        } else if ft.is_file() {
            let path = e.path();
            let ext = path.extension().and_then(|x| x.to_str()).unwrap_or("");
            if SRC_EXTS.contains(&ext) {
                if let Ok(rel) = path.strip_prefix(base) {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        out.push((rel.to_string_lossy().into_owned(), content));
                    }
                }
            }
        }
    }
}

/// Build the file-tree JSON the frontend expects:
/// `{name, type:"dir", path:"", children:[{name,type,path,children?}]}`
pub fn build_tree(root: &Path, id: &str, local_path: Option<&str>) -> Value {
    let base = project_root(root, id, local_path);
    let name = base
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    if !base.exists() {
        return json!({ "name": name, "type": "dir", "path": "", "children": [] });
    }
    json!({ "name": name, "type": "dir", "path": "", "children": walk(&base, &base) })
}

fn walk(base: &Path, dir: &Path) -> Vec<Value> {
    let Ok(rd) = std::fs::read_dir(dir) else { return vec![] };
    let mut entries: Vec<_> = rd.flatten().collect();
    entries.sort_by(|a, b| {
        let ad = a.file_type().map(|t| t.is_dir()).unwrap_or(false);
        let bd = b.file_type().map(|t| t.is_dir()).unwrap_or(false);
        // directories first, then case-insensitive name
        bd.cmp(&ad).then_with(|| {
            a.file_name()
                .to_string_lossy()
                .to_lowercase()
                .cmp(&b.file_name().to_string_lossy().to_lowercase())
        })
    });
    let mut out = Vec::new();
    for e in entries {
        let fname = e.file_name().to_string_lossy().into_owned();
        if fname.starts_with('.') || fname == "__pycache__" {
            continue;
        }
        let Ok(ft) = e.file_type() else { continue };
        let rel = e
            .path()
            .strip_prefix(base)
            .map(|p| p.to_string_lossy().into_owned())
            .unwrap_or_default();
        if ft.is_dir() {
            out.push(json!({ "name": fname, "type": "dir", "path": rel, "children": walk(base, &e.path()) }));
        } else if ft.is_file() {
            out.push(json!({ "name": fname, "type": "file", "path": rel }));
        }
    }
    out
}

// ── Submission / organize / workspace (mirror backend/storage.py) ────────

/// Sanitize a student name for use as a folder segment.
pub fn safe_name(name: &str) -> String {
    let keep: String = name
        .trim()
        .chars()
        .filter(|c| c.is_alphanumeric() || matches!(c, '-' | '_' | ' '))
        .collect();
    let out = keep.trim().replace(' ', "_");
    if out.is_empty() { "student".into() } else { out }
}

const SUBMIT_EXTS: &[&str] = &[
    "cpp", "cc", "cxx", "c", "h", "hpp", "hh", "hxx", "md", "txt", "json",
    "yaml", "yml", "toml", "ini", "cfg", "py", "sh", "cmake", "qmd", "tex",
    "bib", "csv", "xml", "r", "rmd", "sty", "cls", "dtx", "ins", "css", "js",
    "ts", "svg", "html", "pdf",
];
const SUBMIT_NAMES: &[&str] = &[
    "Makefile", "CMakeLists.txt", "compile_flags.txt",
    ".clangd", ".editorconfig", ".gitignore",
];

/// Collect non-executable source/doc files for a submission zip: (relpath, content).
pub fn collect_submission_files(root: &Path, id: &str, local_path: Option<&str>) -> Vec<(String, String)> {
    let base = project_root(root, id, local_path);
    let mut out = Vec::new();
    if !base.exists() {
        return out;
    }
    collect_submit_into(&base, &base, &mut out);
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn collect_submit_into(base: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(rd) = std::fs::read_dir(dir) else { return };
    for e in rd.flatten() {
        let name = e.file_name().to_string_lossy().into_owned();
        // skip dotfiles except the whitelisted ones
        if name.starts_with('.') && !SUBMIT_NAMES.contains(&name.as_str()) {
            continue;
        }
        if name == "__pycache__" {
            continue;
        }
        let Ok(ft) = e.file_type() else { continue };
        if ft.is_dir() {
            collect_submit_into(base, &e.path(), out);
        } else if ft.is_file() {
            let path = e.path();
            let ext = path.extension().and_then(|x| x.to_str()).unwrap_or("");
            let ok_ext = SUBMIT_EXTS.contains(&ext);
            let ok_name = SUBMIT_NAMES.contains(&name.as_str());
            if ok_ext || ok_name {
                if let Ok(rel) = path.strip_prefix(base) {
                    if let Ok(content) = std::fs::read_to_string(&path) {
                        out.push((rel.to_string_lossy().into_owned(), content));
                    }
                }
            }
        }
    }
}

/// Create a submission zip under `submissions_root` and return its path.
/// Zip name: {key}+{counter}.zip
pub fn create_submission_zip(
    submissions_root: &Path,
    key: &str, counter: i64,
    files: &[(String, String)],
    student_name: &str, course: &str, cohort: &str, slot: i64,
    project_title: &str, submitted_at: &str,
) -> anyhow::Result<PathBuf> {
    use std::fs::File;
    use std::io::Write;
    use zip::{write::SimpleFileOptions, CompressionMethod, ZipWriter};

    std::fs::create_dir_all(submissions_root)?;
    let zip_name = format!("{key}+{counter}.zip");
    let zip_path = submissions_root.join(&zip_name);
    let file = File::create(&zip_path)?;
    let mut zw = ZipWriter::new(file);
    let opts = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
    let meta = json!({
        "key": key, "counter": counter,
        "student_name": student_name, "course": course, "cohort": cohort, "slot": slot,
        "project_title": project_title, "submitted_at": submitted_at, "files": names,
    });
    zw.start_file("meta.json", opts)?;
    zw.write_all(serde_json::to_vec_pretty(&meta)?.as_slice())?;
    for (name, content) in files {
        zw.start_file(name, opts)?;
        zw.write_all(content.as_bytes())?;
    }
    zw.finish()?;
    Ok(zip_path)
}

/// Unpack collected zips into {root_folder}/{NN}-{name}/ keeping only the
/// highest-counter zip per key. Returns {organized:[...], errors:[...]}.
pub fn organize_submissions(root_folder: &str, zips_folder: &str, key_lookup: &std::collections::HashMap<String, (i64, String)>) -> Value {
    use std::collections::HashMap;
    use std::fs::File;
    use std::io::Read;

    let root = PathBuf::from(root_folder);
    let _ = std::fs::create_dir_all(&root);
    let zdir = PathBuf::from(zips_folder);
    if !zdir.exists() {
        return json!({ "organized": [], "errors": [format!("zips folder not found: {zips_folder}")] });
    }
    // key -> (counter, path)
    let mut best: HashMap<String, (i64, PathBuf)> = HashMap::new();
    let mut errors: Vec<String> = Vec::new();
    let mut entries: Vec<PathBuf> = std::fs::read_dir(&zdir)
        .into_iter().flatten().flatten().map(|e| e.path()).collect();
    entries.sort();
    for zp in entries {
        if zp.extension().and_then(|e| e.to_str()) != Some("zip") {
            continue;
        }
        let zname = zp.file_name().and_then(|n| n.to_str()).unwrap_or("").to_string();
        let file = match File::open(&zp) { Ok(f) => f, Err(e) => { errors.push(format!("{}: {e}", zname)); continue; } };
        let mut za = match zip::ZipArchive::new(file) { Ok(a) => a, Err(e) => { errors.push(format!("{}: {e}", zname)); continue; } };
        let meta: Value = match za.by_name("meta.json") {
            Ok(mut zf) => {
                let mut buf = Vec::new();
                if zf.read_to_end(&mut buf).is_err() { errors.push(format!("{}: bad meta", zname)); continue; }
                serde_json::from_slice(&buf).unwrap_or(Value::Null)
            }
            Err(_) => { errors.push(format!("{}: no meta.json", zname)); continue; }
        };
        let key = meta.get("key").and_then(|v| v.as_str()).unwrap_or("").to_string();
        let counter = meta.get("counter").and_then(|v| v.as_i64()).unwrap_or(0);
        if !key_lookup.contains_key(&key) {
            errors.push(format!("{}: unknown key (not in this assignment)", zname));
            continue;
        }
        let prev = best.get(&key).map(|(c, _)| *c).unwrap_or(-1);
        if counter > prev {
            best.insert(key, (counter, zp.clone()));
        }
    }

    let mut organized: Vec<Value> = Vec::new();
    for (key, (counter, zp)) in &best {
        let (serial, name) = &key_lookup[key];
        let folder = format!("{:02}-{}", serial, safe_name(name));
        let target = root.join(&folder);
        let _ = std::fs::create_dir_all(&target);
        let target_resolved = target.canonicalize().unwrap_or_else(|_| target.clone());
        let file = match File::open(zp) { Ok(f) => f, Err(e) => { errors.push(format!("{}: {e}", zp.display())); continue; } };
        let mut za = match zip::ZipArchive::new(file) { Ok(a) => a, Err(e) => { errors.push(format!("{}: {e}", zp.display())); continue; } };
        for i in 0..za.len() {
            let mut zf = match za.by_index(i) { Ok(z) => z, Err(_) => continue };
            let mname = zf.name().to_string();
            if mname == "meta.json" || mname.ends_with('/') {
                continue;
            }
            // zip-slip guard
            let dest = target.join(&mname);
            use path_clean::PathClean;
            let dest_clean = dest.clean();
            if dest_clean != target_resolved && !dest_clean.starts_with(&target_resolved) {
                errors.push(format!("{}: skipping unsafe path {:?}", zp.file_name().and_then(|n|n.to_str()).unwrap_or(""), mname));
                continue;
            }
            if let Some(parent) = dest.parent() { let _ = std::fs::create_dir_all(parent); }
            let mut buf = Vec::new();
            if zf.read_to_end(&mut buf).is_ok() {
                let _ = std::fs::write(&dest, &buf);
            }
        }
        organized.push(json!({ "student": name, "serial": serial, "folder": folder, "counter": counter }));
    }
    organized.sort_by_key(|v| v.get("serial").and_then(|s| s.as_i64()).unwrap_or(0));
    json!({ "organized": organized, "errors": errors })
}

/// List immediate sub-directories of `root_folder` as [{name, path(abs)}].
pub fn scan_workspace(root_folder: &str) -> Vec<(String, String)> {
    let root = PathBuf::from(root_folder);
    let mut out = Vec::new();
    let Ok(rd) = std::fs::read_dir(&root) else { return out };
    let mut entries: Vec<_> = rd.flatten().collect();
    entries.sort_by_key(|e| e.file_name().to_string_lossy().to_lowercase());
    for e in entries {
        if let Ok(ft) = e.file_type() {
            let name = e.file_name().to_string_lossy().into_owned();
            if ft.is_dir() && !name.starts_with('.') {
                if let Ok(abs) = e.path().canonicalize() {
                    out.push((name, abs.to_string_lossy().into_owned()));
                }
            }
        }
    }
    out
}

/// Snapshot a project as a git commit. Returns the commit hash, or None.
/// Commit message: `Submission #{seq} {ISO-8601 ms UTC Z}`.
pub fn submission_commit(root: &Path, id: &str, local_path: Option<&str>, seq: i64, student_name: Option<&str>) -> Option<String> {
    use std::process::Command;
    let d = project_root(root, id, local_path);
    if !d.exists() {
        return None;
    }
    let ts = chrono::Utc::now()
        .to_rfc3339_opts(chrono::SecondsFormat::Millis, true);
    let msg = format!("Submission #{seq} {ts}");
    let author = student_name.unwrap_or("Student");
    let _ = Command::new("git").args(["add", "-A"]).current_dir(&d).output();
    let _ = Command::new("git")
        .args(["-c", &format!("user.name={author}"), "-c", "user.email=cppbox@localhost", "commit", "--allow-empty", "-m", &msg])
        .current_dir(&d).output();
    let out = Command::new("git").args(["rev-parse", "HEAD"]).current_dir(&d).output().ok()?;
    let hash = String::from_utf8_lossy(&out.stdout).trim().to_string();
    if hash.is_empty() { None } else { Some(hash) }
}

/// Extract the leading serial from a "NN-name" folder name.
pub fn folder_serial(name: &str) -> Option<i64> {
    let head = name.split('-').next().unwrap_or("");
    head.parse::<i64>().ok()
}
